name: Build Kivy APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk git zip unzip wget curl
          pip install --upgrade pip
          pip install buildozer cython

      - name: Manually Install Python-for-Android  # ✅ FIX: Clone & Install Manually
        run: |
          git clone --depth=1 https://github.com/kivy/python-for-android.git
          cd python-for-android
          pip install .

      - name: Install Android SDK & NDK (Manual Fix)  # ✅ FIX: NDK Manually Install
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$PATH
          
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          
          chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # ✅ MANUALLY INSTALL NDK (FIX)
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "ndk;25.2.9519653"
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export PATH=$ANDROID_NDK:$PATH

      - name: Fix Buildozer Memory Issue  # ✅ Prevent Build Crashes
        run: |
          mkdir -p /home/runner/work/Calculator/Calculator/.buildozer/android/platform/python-for-android
          buildozer android clean  # ✅ Purana Cache Delete Karein
          rm -rf ~/.cython  # ✅ Cython Cache Delete Karein

      - name: Build APK
        env:
          P4A_NO_PREBUILT_DEPS: 1  # ✅ Fix Prebuilt Packages Issue
          P4A_NUM_CORES: 1  # ✅ Single-Core Mode Me Run Karein
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_NDK:$PATH
          
          buildozer -v android debug 2>&1 | tee buildozer_log.txt  # ✅ Build Log Save Karein

      - name: Debugging - Check Bin Folder  # ✅ Bin Folder Exist Check Karein
        run: |
          ls -lah bin/

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Upload Build Log  # ✅ Agar APK fail ho gaya to log file bhejein
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer_log.txt
