name: Build Kivy APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest Version

      - name: Setup Python
        uses: actions/setup-python@v5  # Latest Version
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk git zip unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: kivy-apk
          path: bin/*.apk
