name: Build Kivy APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cleanup Old Buildozer Files
        run: |
          rm -rf .buildozer .gradle .android $HOME/.buildozer $HOME/.gradle $HOME/.android

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk git zip unzip wget curl
          pip install --upgrade pip
          pip install buildozer cython

      - name: Manually Install Python-for-Android
        run: |
          git clone --depth=1 https://github.com/kivy/python-for-android.git
          cd python-for-android
          pip install .

      - name: Install Android SDK & NDK (Manual Install)
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$PATH
          
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          
          chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # ✅ MANUALLY INSTALL NDK
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk.zip
          unzip android-ndk.zip -d $ANDROID_SDK_ROOT/ndk/
          mv $ANDROID_SDK_ROOT/ndk/android-ndk-r25b $ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export PATH=$ANDROID_NDK:$PATH

      - name: Build APK
        env:
          P4A_NO_PREBUILT_DEPS: 1
          P4A_NUM_CORES: 1
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_NDK:$PATH
          
          buildozer -v android debug 2>&1 | tee buildozer_log.txt

      - name: Check APK File Exists
        run: |
          ls -lah bin/
          if [ -f bin/*.apk ]; then
            echo "✅ APK file generated successfully!"
          else
            echo "❌ APK file NOT found! Build failed!"
            exit 1
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer_log.txt
